# General
device: cuda:0
seed: 42

# Dataset
dataset_path: ./data/imagenet  # user should provide ImageNet folder
batch_size: 32
num_workers: 8

# Training
epochs: 10
lr: 2e-4
weight_decay: 0.0
clip_grad_norm: 1e4
scheduler_gamma: 0.99
scheduler_step: 1000

# Model
unet_channels: 256
unet_dim_mults: [1,1,2,3,4]
unet_resnet_groups: 8
unet_learned_sin: true
unet_sin_dim: 32
unet_attention_heads: 4
unet_attention_head_dim: 64

# Interpolant
sigma: 0.1          # noise level for base density