#!/usr/bin/env python3
"""
Reproduction of "Sample-specific Masks for Visual Reprogramming-based Prompting"
This script implements the SMM framework from the paper.
"""
import os
import sys
import time
import argparse
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import torchvision.models as models
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from tqdm import tqdm
from collections import defaultdict
import random

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

class MaskGenerator(nn.Module):
    """
    Lightweight mask generator as described in Section 3.2.
    This is a 5-layer CNN that takes a resized image and outputs a 3-channel mask.
    """
    def __init__(self, in_channels=3, num_layers=5, base_channels=32):
        super(MaskGenerator, self).__init__()
        
        layers = []
        # First layer: input to base_channels
        layers.append(nn.Conv2d(in_channels, base_channels, kernel_size=3, padding=1, bias=False)
        layers.append(nn.BatchNorm2d(base_channels))
        layers.append(nn.ReLU(inplace=True))
        
        # Middle layers: base_channels to base_channels
        for _ in range(num_layers - 2):
            layers.append(nn.Conv2d(base_channels, base_channels, kernel_size=3, padding=1, bias=False)
        layers.append(nn.BatchNorm2d(base_channels))
        layers.append(nn.ReLU(inplace=True)
        
        # Last layer: base_channels to 3 channels for output mask
        layers.append(nn.Conv2d(base_channels, 3, kernel_size=3, padding=1, bias=False)
        
        # Final activation: Sigmoid to ensure values between 0 and 1
        layers.append(nn.Sigmoid())
        
        self.network = nn.Sequential(*layers)
        
        # Initialize weights (as suggested in the paper, we use a standard initialization)
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
    
    def forward(self, x):
        return self.network(x)

class PatchWiseInterpolation(nn.Module):
    """
    Patch-wise interpolation module as described in Section 3.3.
    This module upscales a mask from a smaller size to the original size.
    """
    def __init__(self, patch_size=8):
        super(PatchWiseInterpolation, self).__init__()
        self.patch_size = patch_size
    
    def forward(self, x):
        """
        x: tensor of shape (batch_size, 1, H//l, W//l) or (batch_size, 3, H//l, W//l)
        We assume that the input has been generated by the mask generator
        and we want to upscale it to the original size.
        """
        # Get input shape
        batch_size, channels, height, width = x.shape
        # Calculate scale factor
        scale_factor = self.patch_size
        
        # We'll use nearest neighbor interpolation for simplicity
        # This matches the paper's description of "assigning the same value to surrounding areas"
        x = torch.nn.functional.interpolate(
            x, 
            scale_factor=scale_factor, 
            mode='nearest'
        )
        
        return x

class SMMReprogramming(nn.Module):
    """
    Main SMM framework combining the mask generator and patch-wise interpolation.
    This implements the framework described in Section 3.1 and Algorithm 1.
    """
    def __init__(self, base_model, input_size=224, mask_generator_layers=5, patch_size=8):
        super(SMMReprogramming, self).__init__()
        
        self.base_model = base_model
        self.input_size = input_size
        self.patch_size = patch_size
        self.mask_generator = MaskGenerator(in_channels=3, num_layers=mask_generator_layers)
        self.patch_interpolation = PatchWiseInterpolation(patch_size=patch_size)
        
        # Initialize the noise pattern δ as a zero tensor
        self.delta = nn.Parameter(torch.zeros(3, input_size, input_size))
        
        # Resize function
        self.resize = transforms.Resize((input_size, input_size))
        
        # Define the output mapping function (f_out)
        # We'll use Ilm as described in the paper
        self.output_mapping = None
        self.output_mapping_initialized = False
        
        # Initialize the output mapping
        self.initialize_output_mapping()
    
    def initialize_output_mapping(self):
        """Initialize the output mapping function f_out as described in Section 3.4"""
        # We'll use Ilm as described in the paper
        # This is a one-to-one mapping from Y_P to Y_T
        # For now, we'll initialize it as None and update it during training
        pass
    
    def forward(self, x, update_mask=True):
        """
        Forward pass of the SMM framework.
        x: input image tensor of shape (batch_size, 3, H, W)
        update_mask: if True, update the mask for this batch
        """
        # Resize the input image to the expected size
        x_resized = self.resize(x)
        
        # Generate the mask for this input using the mask generator
        mask = self.mask_generator(x_resized)
        
        # Apply patch-wise interpolation to resize the mask to match the pattern size
        mask_interpolated = self.patch_interpolation(mask)
        
        # Apply the noise pattern δ to the image
        # This implements: f_in(x_i; δ, φ) = r(x_i) + δ ⊙ f_mask(r(x_i) | φ)
        x_reprogrammed = x_resized + self.delta * mask_interpolated
        
        # Pass through the base model
        output = self.base_model(x_reprogrammed)
        
        return output

class OutputMapping(nn.Module):
    """
    Output mapping function f_out as described in Section 3.4.
    This implements the iterative label mapping (Ilm) method.
    """
    def __init__(self, num_classes_target, num_classes_source):
        super(OutputMapping, self).__init__()
        self.num_classes_target = num_classes_target
        self.num_classes_source = num_classes_source
        self.mapping = torch.zeros(num_classes_target)
        self.mapping_initialized = False
        
        # Initialize the mapping
        self.initialize_mapping()
    
    def initialize_mapping(self):
        """Initialize the mapping function as described in Algorithm 4"""
        # We'll use a random one-to-one mapping
        # This is a simplified version of the Ilm method
        self.mapping = torch.randperm(self.num_classes_source)[:self.num_classes_target]
        self.mapping_initialized = True
    
    def forward(self, x):
        """Apply the mapping function to the output"""
        # This is a simplified version of the Ilm method
        # In practice, we would update this mapping based on the predictions
        # For now, we'll use the initialized mapping
        if not self.mapping_initialized:
            self.initialize_mapping()
        
        # Apply the mapping
        return torch.gather(x, 1, self.mapping.to(x.device).long().unsqueeze(0).expand(x.size(0), -1))

def load_model(model_name, num_classes):
    """
    Load a pre-trained model from torchvision
    """
    if model_name == "resnet18":
        model = models.resnet18(pretrained=True)
        model.fc = nn.Linear(model.fc.in_features, num_classes)
    elif model_name == "resnet50":
        model = models.resnet50(pretrained=True)
        model.fc = nn.Linear(model.fc.in_features, num_classes)
    elif model_name == "vit_b32":
        model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_224', pretrained=True)
        model.head = nn.Linear(model.head.in_features, num_classes)
    else:
        raise ValueError(f"Model {model_name} not supported")
    
    # Freeze the model parameters
    for param in model.parameters():
        param.requires_grad = False
    
    return model

def load_dataset(dataset_name, batch_size=256):
    """
    Load a dataset from torchvision
    """
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize((0.485, 0.457, 0.407), (0.225, 0.224, 0.221))
    ])
    
    if dataset_name == "cifar10":
        train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
        test_dataset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)
        num_classes = 10
    elif dataset_name == "cifar100":
        train_dataset = torchvision.datasets.CIFAR100(root='./data', train=True, download=True, transform=transform)
        test_dataset = torchvision.datasets.CIFIFAR100(root='./data', train=False, download=True, transform=transform)
        num_classes = 100
    elif dataset_name == "svhn":
        train_dataset = torchvision.datasets.SVHN(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.SVHN(root='./data', split='test', download=True, transform=transform)
        num_classes = 10
    elif dataset_name == "gtsrb":
        train_dataset = torchvision.datasets.GTSRB(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.GTSRB(root='./data', split='test', download=True, transform=transform)
        num_classes = 43
    elif dataset_name == "flowers102":
        train_dataset = torchvision.datasets.Flowers102(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.Flowers102(root='./data', split='test', download=True, transform=transform)
        num_classes = 102
    elif dataset_name == "dtd":
        train_dataset = torchvision.datasets.DTD(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.DTD(root='./data', split='test', download=True, transform=transform)
        num_classes = 47
    elif dataset_name == "ucf101":
        train_dataset = torchvision.datasets.UCF101(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.UCF101(root='./data', split='test', download=True, transform=transform)
        num_classes = 101
    elif dataset_name == "food101":
        train_dataset = torchvision.datasets.Food101(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.Food101(root='./data', split='test', download=True, transform=transform)
        num_classes = 101
    elif dataset_name == "sun397":
        train_dataset = torchvision.datasets.SUN397(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.SUN397(root='./data', split='test', download=True, transform=transform)
        num_classes = 397
    elif dataset_name == "eurosat":
        train_dataset = torchvision.datasets.EuroSAT(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.EuroSAT(root='./data', split='test', download=True, transform=transform)
        num_classes = 10
    elif dataset_name == "oxfordpets":
        train_dataset = torchvision.datasets.OxfordIIITPet(root='./data', split='train', download=True, transform=transform)
        test_dataset = torchvision.datasets.OxfordIIITPet(root='./data', split='test', download=True, transform=transform)
        num_classes = 37
    else:
        raise ValueError(f"Dataset {dataset_name} not supported")
    
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
    
    return train_loader, test_loader, num_classes

def train_model(model, train_loader, test_loader, num_epochs=20, learning_rate=0.01):
    """
    Train the model using the SMM framework
    """
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)
    
    # Initialize output mapping
    model.output_mapping = OutputMapping(num_classes_target=10, num_classes_source=10)
    
    # Training loop
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0.0
        correct = 0
        total = 0
        
        for batch_idx, (data, target) in enumerate(tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}")):
            data, target = data.to(device), target.to(device)
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()
            total += target.size(0)
        
        # Update output mapping
        # This is a simplified version of the Ilm method
        # In practice, we would update this mapping based on the predictions
        model.output_mapping.mapping = torch.randperm(model.output_mapping.num_classes_source)[:model.output_mapping.num_classes_target]
        
        # Evaluate on test set
        model.eval()
        test_loss = 0
        correct = 0
        total = 0
        with torch.no_grad():
            for data, target in test_loader:
                data, target = data.to(device), target.to(device)
                output = model(data)
            loss = criterion(output, target)
            test_loss += loss.item()
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()
            total += target.size(0)
        
        print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {train_loss/len(train_loader):.4f}, Train Acc: {100. * correct / total:.2f}, Test Loss: {test_loss/len(test_loader):.4f}, Test Acc: {100. * correct / total:.2f}")

def main():
    """
    Main function to reproduce the results from the paper
    """
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Reproduce SMM results from the paper')
    parser.add_argument('--model', type=str, default='resnet18', help='Model to use (resnet18, resnet50, vit_b32)')
    parser.add_argument('--dataset', type=str, default='cifar10', help='Dataset to use (cifar10, cifar100, svhn, gtsrb, flowers102, dtd, ucf101, food101, sun397, eurosat, oxfordpets)')
    parser.add_argument('--epochs', type=int, default=20, help='Number of epochs to train')
    parser.add_argument('--batch_size', type=int, default=256, help='Batch size')
    parser.add_argument('--learning_rate', type=float, default=0.01, help='Learning rate')
    parser.add_argument('--mask_layers', type=int, default=5, help='Number of layers in mask generator')
    parser.add_argument('--patch_size', type=int, default=8, help='Patch size for interpolation')
    args = parser.parse_args()
    
    # Set up directories
    os.makedirs('data', exist_ok=True)
    os.makedirs('models', exist_ok=True)
    os.makedirs('results', exist_ok=True)
    
    # Load dataset
    print(f"Loading dataset: {args.dataset}")
    train_loader, test_loader, num_classes = load_dataset(args.dataset, args.batch_size)
    
    # Load model
    print(f"Loading model: {args.model}")
    base_model = load_model(args.model, num_classes)
    
    # Initialize SMM framework
    print("Initializing SMM framework...")
    smm_model = SMMReprogramming(base_model, mask_generator_layers=args.mask_layers, patch_size=args.patch_size)
    smm_model.to(device)
    
    # Train model
    print("Training model...")
    train_model(smm_model, train_loader, test_loader, num_epochs=args.epochs, learning_rate=args.learning_rate)
    
    # Save model
    model_path = f"models/{args.model}_{args.dataset}_smm.pth"
    torch.save(smm_model.state_dict(), model_path)
    print(f"Model saved to: {model_path}")
    
    # Save results
    print("Saving results...")
    results = {
        'model': args.model,
        'dataset': args.dataset,
        'epochs': args.epochs,
        'batch_size': args.batch_size,
        'learning_rate': args.learning_rate,
        'mask_layers': args.mask_layers,
        'patch_size': args.patch_size
    }
    
    results_path = f"results/{args.model}_{args.dataset}_results.json"
    import json
    with open(results_path, 'w') as f:
        json.dump(results, f)
    
    print(f"Results saved to: {results_path}")
    
    print("Reproduction completed successfully!")

if __name__ == '__main__':
    main()