#!/usr/bin/env python
# train.py
import argparse
import torch
from tqdm import tqdm
from adapters import Adapter
from utils import (
    load_tokenizer,
    generate_candidates,
    prepare_batch,
    compute_nce_loss,
    load_gsm8k,
)

def main(args):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    tokenizer = load_tokenizer(args.base_model)
    adapter = Adapter(args.base_model).to(device)

    optimizer = torch.optim.AdamW(adapter.parameters(), lr=args.lr)
    # The encoder is frozen; we only train the linear head
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1, gamma=0.9)

    train_ds = load_gsm8k(split=f"train[:{args.train_frac}%]")
    val_ds = load_gsm8k(split=f"validation[:{args.val_frac}%]")

    for epoch in range(1, args.epochs + 1):
        adapter.train()
        epoch_loss = 0.0
        for example in tqdm(train_ds, desc=f"Epoch {epoch}"):
            prompt = example["question"]
            # Generate candidates from the black‑box LM
            candidates = generate_candidates(
                tokenizer,
                prompt,
                args.base_model,
                num_candidates=args.k,
                max_length=args.max_length,
                temperature=args.temperature,
            )
            # Build a batch: the positive sample is the ground‑truth answer
            batch_texts = [example["answer"]] + candidates
            enc = prepare_batch({"text": batch_texts}, tokenizer)
            input_ids = enc["input_ids"].to(device)
            attention_mask = enc["attention_mask"].to(device)

            scores = adapter(input_ids, attention_mask)
            # Positive mask: first element is the ground truth
            pos_mask = torch.zeros_like(scores, dtype=torch.bool)
            pos_mask[0] = True

            loss = compute_nce_loss(scores, pos_mask)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        scheduler.step()
        print(f"Epoch {epoch} – loss: {epoch_loss / len(train_ds):.4f}")

        # Validation
        acc = evaluate(adapter, tokenizer, val_ds, num_candidates=args.k)
        print(f"Validation accuracy: {acc:.4f}")

    # Save checkpoint
    torch.save(adapter.state_dict(), args.output_dir + "/adapter.pt")
    print("Training finished – checkpoint saved.")


def evaluate(adapter, tokenizer, test_ds, num_candidates=3):
    """
    Simple evaluation routine – returns accuracy.
    """
    from utils import evaluate_adapter
    return evaluate_adapter(adapter, tokenizer, test_ds, num_candidates=num_candidates)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train BBox‑Adapter on GSM8K.")
    parser.add_argument("--base-model", type=str, default="microsoft/deberta-v3-base",
                        help="Name of the encoder model used in the adapter.")
    parser.add_argument("--k", type=int, default=3,
                        help="Number of candidates generated by the black‑box LM.")
    parser.add_argument("--max-length", type=int, default=256,
                        help="Maximum output length for candidate generation.")
    parser.add_argument("--temperature", type=float, default=0.7,
                        help="Sampling temperature for generation.")
    parser.add_argument("--epochs", type=int, default=3,
                        help="Number of training epochs.")
    parser.add_argument("--lr", type=float, default=5e-6,
                        help="Learning rate for the adapter head.")
    parser.add_argument("--train-fraction", type=int, default=10,
                        help="Percentage of training set to use (default 10%).")
    parser.add_argument("--val-fraction", type=int, default=20,
                        help="Percentage of validation set to use (default 20%).")
    parser.add_argument("--output-dir", type=str, default="./checkpoints",
                        help="Directory to store checkpoints.")
    args = parser.parse_args()

    import os
    os.makedirs(args.output_dir, exist_ok=True)
    main(args)