"""Utility functions for the Simformer toy implementation."""

import jax
import jax.numpy as jnp
from functools import partial
import numpy as np
from typing import Tuple, Dict

# --------------------------------------------------------------
# Diffusion schedule (Variance‑Exploding SDE)
# --------------------------------------------------------------
def sigma_t(t: float, sigma_min: float = 0.0001, sigma_max: float = 15.0) -> float:
    """Scale function σ(t) for VESDE."""
    return sigma_min * (sigma_max / sigma_min) ** t


def perturb(x: jnp.ndarray,
            t: float,
            key: jax.random.PRNGKey,
            sigma_min: float = 0.0001,
            sigma_max: float = 15.0) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """
    Add Gaussian noise to a clean sample x at diffusion time t.
    Returns noisy sample and the noise term.
    """
    σ = sigma_t(t, sigma_min, sigma_max)
    eps = jax.random.normal(key, shape=x.shape)
    return x + σ * eps, eps


# --------------------------------------------------------------
# Two‑Moons simulator (parameter → data)
# --------------------------------------------------------------
def two_moons_sampler(key: jax.random.PRNGKey,
                      n_samples: int) -> Tuple[jnp.ndarray, jnp.ndarray]:
    """
    Sample n_samples pairs (θ, x) from the toy Two‑Moons simulation.
    θ ∈ ℝ² uniform in [−1, 1], x ∈ ℝ² generated by a deterministic transform.
    """
    θ_key, noise_key = jax.random.split(key)
    θ = jax.random.uniform(θ_key, shape=(n_samples, 2), minval=-1.0, maxval=1.0)

    # Parameters to data mapping (toy version of the paper's Two‑Moons)
    def θ_to_x(theta):
        # Convert to polar coordinates
        r = 0.3 + 0.05 * theta[:, 0]
        α = jnp.pi * (theta[:, 1] + 1.0) / 2.0  # map in [0, π]
        x1 = r * jnp.cos(α) + 0.25
        x2 = r * jnp.sin(α)
        # Add deterministic shift based on θ
        shift = (-jnp.abs(theta[:, 0] + theta[:, 1]) / jnp.sqrt(2),
                 ( -theta[:, 0] + theta[:, 1]) / jnp.sqrt(2))
        return jnp.stack([x1 + shift[0], x2 + shift[1]], axis=1)

    x_clean = θ_to_x(θ)

    # Add observation noise
    noise = jax.random.normal(noise_key, shape=x_clean.shape) * 0.05
    x = x_clean + noise

    return θ, x