# This workflow is optional and only for developers
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
      - name: Install python deps
        run: |
          pip install -r requirements.txt
      - name: Run reproduction
        run: |
          bash reproduce.sh